### ISSUE TITLE
Database diagram review

### ISSUE THREAD

**Issue by Sergei-Lukashenko** [Lomonosov-Dmitry/java-filmorate#3]
1. По полю Rating в таблице Films мне видится, что будет достаточно завести строковое поле и в нем описать все возможные значения возрастных рейтингов с помощью ограничения БД, т.к. эти значения постоянные. По моему, эти значения утверждаются гос-органами и не меняются потом (или меняются очень редко). Тогда таблица Rating не нужна
2. Таблица Genre, наверное, должна быть таблицей-связкой между фильмами и жанрами? Я бы тогда описал отдельную таблицу-справочник жанров с двумя колонками genre_id PK + name и сделал таблицу-связку film_genres на замену твоей genres. В таблице film_genres будут 2 поля film_id и genre_id,  которые оба входят в первичный ключ, а также являются внешними ключами и ссылаются на ID-шники в таблицах FIlm и "справочник жанров". Таким образом мы смоделируем связь "многие-ко-многим" между жанрами и фильмами - то есть один фильм может соответствовать нескольким жанрам и каждый жанр может подходить ко многим фильмам.
3. В таблице Likes не хватает первичного ключа - оба поля должны входить в этот первичный ключ, чтобы ту же связь "многие-ко-многим" сделать. Я бы еще переименовал названия колонок в этой таблице - Film в film_id, а User в user_id - так они будут более говорящими
4. В таблице Friendship тоже не хватает первичного ключа - в него стоит включить поля User и Friend, возможно стоит их также переименовать, чтобы в имена колонок входило обозначение "id"
5. Нужно ли в таблице Friendship иметь два поля Friendship и Request? Нам по заданию нужно добавить "статус для связи «дружба» между двумя пользователями" - это выглядит как одно (дополнительное к ключам) поле в таблице Friendship, например, это может целочисленный Status со значениями "подтверждено" и "не подтверждено" или логическое bool Confirmed. А наличие дружбы с том или ином статусе между пользователями будет обозначать присутствие записи с их ID-шниками в таблице Friendship

**Comment by Lomonosov-Dmitry** [comment]
1. Это не будет соответствовать первой нормальной форме: отсутствие списков и массивов в любом виде и только атомарные значения.
2. На мой взгляд еще одна таблица не нужна. Пока получается, что я могу из таблицы Genre вытащить одним простым запросом как все фильмы конкретного жанра, так и все жанры, к которым относится фильм. Не вижу выгоды в еще одной таблице.
3. Согласен, мой косяк, проглядел.
4. Аналогично п.3
5. Да, так действительно будет проще, согласен

**Comment by Sergei-Lukashenko** [comment]
1. Да, ты прав. Если фильм соответствует нескольким категориям, то нужна отдельная таблица. Тогда проверь пожалуйста таблицу Rating - там первичный ключ из одного поля ID рейтинга. В таком варианте нельзя будет один и тот же рейтинг разным фильмам присвоить. Это можно решить через включение ID фильма в первичный ключ
2. Здесь тот же вопрос - сейчас в таблице Genre первичный ключ состоит одного поля ID и видимо его нужно будет расширить

**Comment by Lomonosov-Dmitry** [comment]
1. У одного фильма может быть только один рейтинг - без вариантов. Тут неверно поставлена связь, нужно 1-1
2. А вот тут не понимаю зачем. Одному рейтингу может соответствовать много фильмов, вроде все правильно

**Comment by Sergei-Lukashenko** [comment]
1. Ok, но там, где связь один-к-одному, можно объединить все в одной таблице - где-то в теории про это было. Тут на твой выбор, как есть, все подходит, по моему
2. Тут про жанры речь - один фильм может соответствовать нескольким жанрам. Например, это комедия и боевик. И наборот, для одного жанра (например, комедия) могут снять несколько фильмов. То есть тут связи многие-ко многим. Если диаграмм это подразумевает (я не силен в обозначениях связей), то все Ok. Но мнея кажется, при создании таблицв первичый ключ должен быть множественным, чтобы такую связб поддержать

**Comment by Lomonosov-Dmitry** [comment]
1. Если следовать нормальным формам, как они описаны, то должно быть так, как на диаграмме. Но я тоже сталкивался с тем, что можно подставлять набор уникальных значений. Может быть так делать не правильно.
2. Тоже не силен в связях, учимся же :) Диаграмма подразумевает, что одному жанру может соответствовать много фильмов. Делать многие ко многим избыточно, как мне кажется, потому что можно сделать достаточно простые отборы, реализующие получение как всех фильмов жанра, так и всех жанров фильма. Я когда-то где-то читал, что связи многие ко многим надо избегать. Может это уже не актуально, я не знаю, но пока такая схема мне видится оптимальной

**Comment by Sergei-Lukashenko** [comment]
OK. Review диаграммы предлагаю считать завершенным.
Если огрехи остались, можно будет на финальном проекте 12-го спринта подчинить, я думаю. Там уже настоящие ревьюеры возьмутся за дело :)
